Repository Decathlon/vitamin-ios, pull requests merged in 2022-12, with the labels that each got.

#92 feat: badge for SwiftUI
  README.md
  Showcase/Application/Core/Components/Badge/BadgeModel.swift
  Showcase/Application/SwiftUI/Components/Badge/BadgesView.swift
  Showcase/Application/SwiftUI/Main/MainView.swift
  Showcase/Application/SwiftUI/Utils/Accessibility/AdaptiveStack.swift
  Showcase/Application/SwiftUI/Utils/Accessibility/DynamicFrameModifier.swift
  Showcase/Vitamin Showcase.xcodeproj/project.pbxproj
  Sources/VitaminCore/Components/Badge/VitaminBadgeLogic.swift
  Sources/VitaminCore/Components/Badge/VitaminBadgeSize.swift
  Sources/VitaminCore/Components/Badge/VitaminBadgeVariant.swift
  Sources/VitaminCore/Foundations/Typography/TextStyles.swift
  Sources/VitaminSwiftUI/Components/Badge/README.md
  Sources/VitaminSwiftUI/Components/Badge/VitaminBadge.swift
  Sources/VitaminSwiftUI/Components/Badge/VitaminBadgeModifier.swift
  Sources/VitaminSwiftUI/Utils/Shape+Fill.swift
  Sources/VitaminSwiftUI/Utils/View+SizeChange.swift
  Sources/VitaminUIKit/Components/Badge/README.md
  Sources/VitaminUIKit/Components/Badge/VitaminBadge.swift
Labels: enhancement 🚀

#102 fix: enforce title color when title is set to avoid weird behaviours
  Sources/VitaminUIKit/Components/Button/VitaminButton.swift
Labels: bug 🐛

#104 feat: add new assets (payments)
  Showcase/Application/Core/Foundations/Assets/AssetsModel.swift
  Showcase/Application/UIKit/Foundations/Assets/AssetsViewController.swift
  Sources/VitaminCore/Foundations/Assets/VitaminAssets.swift
  Sources/VitaminCore/Foundations/Assets/VitaminAssets.xcassets/payment/ChequePayment.imageset/ChequePayment.pdf
  Sources/VitaminCore/Foundations/Assets/VitaminAssets.xcassets/payment/ChequePayment.imageset/Contents.json
  Sources/VitaminCore/Foundations/Assets/VitaminAssets.xcassets/payment/GiftCardPayment.imageset/Contents.json
  Sources/VitaminCore/Foundations/Assets/VitaminAssets.xcassets/payment/GiftCardPayment.imageset/GiftCardPayment.pdf
  Sources/VitaminCore/Foundations/Assets/VitaminAssets.xcassets/payment/Wallet.imageset/Contents.json
  Sources/VitaminCore/Foundations/Assets/VitaminAssets.xcassets/payment/Wallet.imageset/Wallet.pdf
Labels: enhancement 🚀, assets 🏞, run 💨

#105 feat: add new icons
  Showcase/Application/Core/Foundations/Icons/IconsModel.swift
  Showcase/Application/UIKit/Foundations/Icons/IconsViewController.swift
  Sources/VitaminCore/Foundations/Icons/Vitamix.swift
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/fill/design/tools.imageset/Contents.json
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/fill/design/tools.imageset/tools-fill.pdf
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/fill/device/tablet.imageset/Contents.json
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/fill/device/tablet.imageset/tablet-fill.pdf
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/fill/map/run.imageset/Contents.json
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/fill/map/run.imageset/run-fill.pdf
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/fill/others/hourglass.imageset/Contents.json
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/fill/others/hourglass.imageset/hourglass-fill.pdf
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/fill/others/sparkles.imageset/Contents.json
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/fill/others/sparkles.imageset/sparkles-fill.pdf
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/fill/system/logout.imageset/Contents.json
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/fill/system/logout.imageset/logout-fill.pdf
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/line/design/tools.imageset/Contents.json
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/line/design/tools.imageset/tools-line.pdf
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/line/device/tablet.imageset/Contents.json
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/line/device/tablet.imageset/tablet-line.pdf
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/line/map/run.imageset/Contents.json
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/line/map/run.imageset/run-line.pdf
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/line/others/hourglass.imageset/Contents.json
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/line/others/hourglass.imageset/hourglass-line.pdf
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/line/others/sparkles.imageset/Contents.json
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/line/others/sparkles.imageset/sparkles-line.pdf
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/line/system/logout.imageset/Contents.json
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/line/system/logout.imageset/logout-line.pdf
Labels: enhancement 🚀, icons ✨, run 💨

#100 feat: swiftui vitamin textfield
  Package.swift
  README.md
  Showcase/Application/Core/Components/TextField/TextFieldModel.swift
  Showcase/Application/SwiftUI/Components/TextField/TextFieldsView.swift
  Showcase/Application/SwiftUI/Components/TextField/Views/VitaminTextFieldView.swift
  Showcase/Application/SwiftUI/Main/MainView.swift
  Showcase/Application/SwiftUI/Utils/Modifiers/OnChangeModifier.swift
  Showcase/Application/UIKit/Components/TextField/Cell/TextFieldTableViewCell.swift
  Showcase/Application/UIKit/Components/TextField/TextFieldViewController.swift
  Showcase/Vitamin Showcase.xcodeproj/project.pbxproj
  Sources/VitaminCore/Components/TextField/VitaminTextFieldState.swift
  Sources/VitaminCore/Components/TextField/VitaminTextFieldStyle.swift
  Sources/VitaminCore/Utils/Accessibility/ScaledValue.swift
  Sources/VitaminSwiftUI/Components/TextField/README.md
  Sources/VitaminSwiftUI/Components/TextField/VitaminTextField.swift
  Sources/VitaminSwiftUI/Components/TextField/VitaminTextFieldConfiguration.swift
  Sources/VitaminSwiftUI/Components/TextField/VitaminTextFieldModifier.swift
  Sources/VitaminUIKit/Components/TextField/README.md
  Sources/VitaminUIKit/Components/TextField/VitaminTextField+Configuration.swift
  Sources/VitaminUIKit/Components/TextField/VitaminTextField.swift
Labels: enhancement 🚀, design request 🙌
