Repository Decathlon/vitamin-ios, pull requests merged in 2023-03, with the labels that each got.

#121 fix: UIKit VitaminTextfield text color
  Sources/VitaminCore/Components/TextField/VitaminTextFieldState.swift
Labels: bug 🐛, run 💨

#119 ci: update deploy workflow
  Scripts/set_version.sh
  bitrise.yml
Labels: config 🛠, run 💨

#122 docs: update readme install section
  README.md
  Scripts/set_version.sh
Labels: documentation 📝, run 💨

#111 feat: chip implementation for uikit
  Package.swift
  Showcase/Application/UIKit/Components/Chip/Cell/ChipTableVewCell.swift
  Showcase/Application/UIKit/Components/Chip/Cell/ChipTableViewCell.xib
  Showcase/Application/UIKit/Components/Chip/ChipViewController.swift
  Showcase/Application/UIKit/Main/MainTableViewController.swift
  Showcase/Vitamin Showcase.xcodeproj/project.pbxproj
  Sources/VitaminCore/Components/Chip/VitaminChipSize.swift
  Sources/VitaminUIKit/Components/Chip/README.md
  Sources/VitaminUIKit/Components/Chip/VitaminChip.swift
  Sources/VitaminUIKit/Components/Chip/VitaminChipSize+Padding.swift
  Sources/VitaminUIKit/Components/Chip/VitaminChipVariant.swift
Labels: enhancement 🚀, Ready for Design Review, UIKit, build 🏗

#125 fix: set tintAdjustmentMode to .normal
  Sources/VitaminUIKit/Components/Button/VitaminButton.swift
Labels: bug 🐛, run 💨

#124 feat: swiftui fullwidth button
  Showcase/Application/SwiftUI/Components/Button/ButtonsView.swift
  Sources/VitaminSwiftUI/Components/Button/README.md
  Sources/VitaminSwiftUI/Components/Button/VitaminButton.swift
Labels: enhancement 🚀, run 💨

#115 feat: SegmentedControl UIKit implementation
  Package.swift
  README.md
  Showcase/Application/UIKit/Components/SegmentedControl/Sample/SampleLabelViewController.swift
  Showcase/Application/UIKit/Components/SegmentedControl/SegmentedControlViewController.swift
  Showcase/Application/UIKit/Main/MainTableViewController.swift
  Showcase/Vitamin Showcase.xcodeproj/project.pbxproj
  Sources/VitaminUIKit/Components/SegmentedControl/README.md
  Sources/VitaminUIKit/Components/SegmentedControl/VitaminSegmentedControl.swift
  Sources/VitaminUIKit/Components/SegmentedControl/VitaminSegmentedControlController.swift
Labels: enhancement 🚀, Ready for Design Review, UIKit, build 🏗

#108 feat: UIKit badge size
  Showcase/Application/UIKit/Components/Badge/BadgesViewController.swift
  Showcase/Application/UIKit/Components/Badge/Cell/BadgeCollectionViewCell.swift
  Showcase/Application/UIKit/Components/Badge/Cell/BadgeCollectionViewCell.xib
  Showcase/Vitamin Showcase.xcodeproj/project.pbxproj
  Sources/VitaminCore/Components/Badge/VitaminBadgeVariant.swift
  Sources/VitaminUIKit/Components/Badge/README.md
  Sources/VitaminUIKit/Components/Badge/VitaminBadge.swift
Labels: enhancement 🚀, Ready for Design Review, UIKit, run 💨

#83 feat(deployment_target): Update Deployment Target to iOS 12 + warning fixes
  .swiftpm/xcode/xcshareddata/xcschemes/Vitamin.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/VitaminCore.xcscheme
  .swiftpm/xcode/xcshareddata/xcschemes/VitaminSwiftUI.xcscheme
  Package.swift
  Showcase/Vitamin Showcase.xcodeproj/project.pbxproj
  Showcase/Vitamin Showcase.xcodeproj/xcshareddata/xcschemes/Vitamin Showcase.xcscheme
  Vitamin.podspec
  VitaminCore.podspec
Labels: config 🛠, run 💨

#132 feat: update icons
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/Contents.json
  Sources/VitaminSwiftUI/Foundations/Icons/Vitamix+SwiftUI.swift
Labels: enhancement 🚀, icons ✨, run 💨

#135 docs: add important note
  .github/ISSUE_TEMPLATE/feature_or_improvement_request.md
  .github/ISSUE_TEMPLATE/new_component_request.md
  README.md
Labels: documentation 📝, run 💨

#134 feat: update icons showcase
  Showcase/Application/Core/Foundations/Icons/IconsModel+Sections.swift
Labels: enhancement 🚀, icons ✨, run 💨
