Repository Decathlon/vitamin-ios, pull requests merged in 2023-02, with the labels that each got.

#114 feat: add new icons
  Showcase/Application/Core/Foundations/Icons/IconsModel.swift
  Sources/VitaminCore/Foundations/Icons/Vitamix.swift
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/fill/finance/shopping_bag.imageset/Contents.json
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/fill/finance/shopping_bag.imageset/shopping-bag-fill.pdf
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/fill/media/volume_alert.imageset/Contents.json
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/fill/media/volume_alert.imageset/volume-alert-fill.pdf
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/fill/others/seed_1.imageset/Contents.json
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/fill/others/seed_1.imageset/seed-1-fill.pdf
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/fill/others/seed_2.imageset/Contents.json
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/fill/others/seed_2.imageset/seed-2-fill.pdf
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/fill/others/seed_3.imageset/Contents.json
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/fill/others/seed_3.imageset/seed-3-fill.pdf
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/line/finance/shopping_bag.imageset/Contents.json
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/line/finance/shopping_bag.imageset/shopping-bag-line.pdf
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/line/media/volume_alert.imageset/Contents.json
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/line/media/volume_alert.imageset/volume-alert-line.pdf
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/line/others/seed_1.imageset/Contents.json
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/line/others/seed_1.imageset/seed-1-line.pdf
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/line/others/seed_2.imageset/Contents.json
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/line/others/seed_2.imageset/seed-2-line.pdf
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/line/others/seed_3.imageset/Contents.json
  Sources/VitaminCore/Foundations/Icons/Vitamix.xcassets/line/others/seed_3.imageset/seed-3-line.pdf
Labels: enhancement 🚀, icons ✨, run 💨

#112 ci: fix deploy workflow
  bitrise.yml
Labels: config 🛠, run 💨

#118 fix: snackbar label width miscomputed when image is set
  Sources/VitaminUIKit/Components/Snackbar/README.md
  Sources/VitaminUIKit/Components/Snackbar/VitaminSnackbar+Dismiss.swift
  Sources/VitaminUIKit/Components/Snackbar/VitaminSnackbar.swift
Labels: bug 🐛, run 💨
